### ISSUE TITLE
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font

### ISSUE THREAD

**Issue by nandini12396** [react-native-community/react-native-device-info#694]
# Bug

I am getting the following errors: 
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontVariationSettings
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:ttcIndex
ERROR: In <declare-styleable> GradientColor, unable to find attribute android:endX
ERROR: In <declare-styleable> GradientColor, unable to find attribute android:endY
ERROR: In <declare-styleable> GradientColor, unable to find attribute android:startX
ERROR: In <declare-styleable> GradientColor, unable to find attribute android:startY
ERROR: In <declare-styleable> GradientColorItem, unable to find attribute android:offset

:react-native-device-info:processReleaseResources FAILED          

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-device-info:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

## Environment info
Environment:
  OS: Windows 10
  Node: 10.13.0
  Yarn: 1.12.3
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.2 => 16.3.2
  react-native: 0.55.4 => 0.55.4
React native info output:

    "react-native-device-info": "^0.21.5",

**Comment by javascriptNode** [comment]
我也遇到了就是今天

**Comment by myshowject** [comment]
我也遇到这个报错

**Comment by cheneywan** [comment]
The same problem

**Comment by nandini12396** [comment]
Any solution? Tried using older version also. Blocked completely!

**Comment by Janain** [comment]
版本升级后，项目跑不起来了，sdk之前是26，今天项目跑不起来了 ，是因为androidx库，android.supoort不一致，是这个问题导致的吗，求赐教下？？？？在线等!!急急急

**Comment by mikehardy** [comment]
that's pretty odd - have you guys tried upgrading, we're on 2.1.2 now and the only version listed here is very old. We just pushed a release that limits the play services dependency to a pre-AndroidX version, as that may cause build breaks - 2.1.2 has that. The changes from 0.x.x to 1.x.x and from 1.x.x to 2.x.x are very easy to adapt to, nothing serious from a breaking change perspective

**Comment by Janain** [comment]
After the version is upgraded, the project can't run. The sdk was 26 before. Today, the project can't run. It is because the androidx library and android.supoort are inconsistent. Is this caused by this problem? ? ? ? Online, etc.!

**Comment by Janain** [comment]
You said that you just retired the previous version, but my project still can't run?

**Comment by dandan6002** [comment]
My project can't run up.

**Comment by MikePodgorniy** [comment]
the very old "react-native-device-info": "0.24.0" is broke too

**Comment by nandini12396** [comment]
same for me

**Comment by Janain** [comment]
> 我也是

你是什么问题 ，项目能起来不

**Comment by myshowject** [comment]
the very old"react-native-device-info": "^0.12.0" is broke too

**Comment by tututututututu** [comment]
add  this code to your project build.gradle
solved
ext {
    buildToolsVersion = "28.0.3"
    minSdkVersion = 18
    compileSdkVersion = 28
    targetSdkVersion = 28
    supportLibVersion = "28.0.0"
    googlePlayServicesVersion="15.0.1"
}

**Comment by Janain** [comment]
> 将此代码添加到您的项目build.gradle 
> 解决了
> ext { 
> buildToolsVersion =“28.0.3” 
> minSdkVersion = 18 
> compileSdkVersion = 28 
> targetSdkVersion = 28 
> supportLibVersion =“28.0.0” 
> googlePlayServicesVersion =“15.0.1” 
> }

那我只想把sdk依赖停留在26，所以这怎么破？
Then I just want to keep the sdk dependency at 26, so how is this broken?

**Comment by ctysc2** [comment]
> > 将此代码添加到您的项目build.gradle
> > 解决了
> > ext {
> > buildToolsVersion =“28.0.3”
> > minSdkVersion = 18
> > compileSdkVersion = 28
> > targetSdkVersion = 28
> > supportLibVersion =“28.0.0”
> > googlePlayServicesVersion =“15.0.1”
> > }
> 
> 那我只想把sdk依赖停留在26，所以这怎么破？
> Then I just want to keep the sdk dependency at 26, so how is this broken?

重点是这句:googlePlayServicesVersion =“15.0.1”

**Comment by tututututututu** [comment]
> > 将此代码添加到您的项目build.gradle
> > 解决了
> > ext {
> > buildToolsVersion =“28.0.3”
> > minSdkVersion = 18
> > compileSdkVersion = 28
> > targetSdkVersion = 28
> > supportLibVersion =“28.0.0”
> > googlePlayServicesVersion =“15.0.1”
> > }
> 
> 那我只想把sdk依赖停留在26，所以这怎么破？
> Then I just want to keep the sdk dependency at 26, so how is this broken?

just add googlePlayServicesVersion="15.0.1"

**Comment by charon120** [comment]
node_modules/react-native-device-info/android/build.gradle
def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION    = "15.0.1"

**Comment by tututututututu** [comment]
> THINKS!@tututututututu
> node_modules/react-native-device-info/android/build.gradle
> def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "15.0.1"

why not define ext googlePlayServicesVersion to your project build.gradle are you maintenance by your self?

**Comment by Janain** [comment]
谢谢 已解决

**Comment by dandan6002** [comment]
> because compile "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"
> the googlePlayServicesVersion default is use "+" and com.google.android.gms:play-services-gcm update today and bringin androidX
> 
> add this code to your project build.gradle
> solved
> ext {
> buildToolsVersion = "28.0.3"
> minSdkVersion = 18
> compileSdkVersion = 28
> targetSdkVersion = 28
> supportLibVersion = "28.0.0"
> googlePlayServicesVersion="15.0.1"
> }

thank you!

**Comment by Aj1402** [comment]
> > THINKS!@tututututututu
> > node_modules/react-native-device-info/android/build.gradle
> > def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "15.0.1"
> 
> why not define ext googlePlayServicesVersion to your project build.gradle are you maintenance by your self?

Worked :)

**Comment by nandini12396** [comment]
> because compile "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"
> the googlePlayServicesVersion default is use "+" and com.google.android.gms:play-services-gcm update today and bringin androidX
> 
> add this code to your project build.gradle
> solved
> ext {
> buildToolsVersion = "28.0.3"
> minSdkVersion = 18
> compileSdkVersion = 28
> targetSdkVersion = 28
> supportLibVersion = "28.0.0"
> googlePlayServicesVersion="15.0.1"
> }

Worked for me. Thank you! Closing it

**Comment by LsFern** [comment]
If you don't want to use this field, you can pull this plug-in out and comment the following code. That's it.
It's easy to maintain later

![TIM截图20190618173944](https://user-images.githubusercontent.com/32630118/59671390-262a5d80-91f0-11e9-8870-580b512ae8d1.png)
![TIM截图20190618174004](https://user-images.githubusercontent.com/32630118/59671403-29bde480-91f0-11e9-9aa8-095047e85a41.png)

**Comment by mikehardy** [comment]
@LsFern that is true, but not great advice unless coupled with a pointer to the 'patch-package' npm, as maintaining modified node_modules differences is dangerous otherwise - your changes could be wiped out any time.

Adding an ext {} block to android/build.gradle with the play services dependency is better advice (it is easy and everyone should do it or you are open to other problems), but even better is to just update your compileSdk to 28 and targetSdk to 28 since Google will force you to shortly anyway and use the 2.1.2 version...

**Comment by HanAsteroid** [comment]
this problem lost me a full day

**Comment by mikehardy** [comment]
Gigantic distributed systems with free but loosely couple dependencies are amazing and save you days with all their free functionality, but they do not digest breaking change well, no.

**Comment by myshowject** [comment]
我现在还没解决，真的服气

**Comment by HanAsteroid** [comment]
Thanks for your resolution, I just complained about sorry.

**Comment by mikehardy** [comment]
@HanAsteroid no worries, honestly it cost me half a day building jetifier so people could have a bridge to use AndroidX https://github.com/mikehardy/jetifier - it's going to be a messy transition in the react-native ecosystem

**Comment by 2qiaoyu** [comment]
for the old version like '0.12.1',find /node_modules/react-native-device-info/android/build.gradle,
modify 'com.google.android.gms:play-services-gcm:+' to 'com.google.android.gms:play-services-gcm:15.0.1'

**Comment by mikehardy** [comment]
Use patch-package rather than modifying in node_modules directly, that way it will be persistent

**Comment by HighSoftWare96** [comment]
> because compile "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"
> the googlePlayServicesVersion default is use "+" and com.google.android.gms:play-services-gcm update today and bringin androidX
> 
> add this code to your project build.gradle
> solved
> ext {
> buildToolsVersion = "28.0.3"
> minSdkVersion = 18
> compileSdkVersion = 28
> targetSdkVersion = 28
> supportLibVersion = "28.0.0"
> googlePlayServicesVersion="15.0.1"
> }

I tried with this solution and with react-native-device-info latest version but the issue persist...

**Comment by tututututututu** [comment]
> > because compile "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"
> > the googlePlayServicesVersion default is use "+" and com.google.android.gms:play-services-gcm update today and bringin androidX
> > add this code to your project build.gradle
> > solved
> > ext {
> > buildToolsVersion = "28.0.3"
> > minSdkVersion = 18
> > compileSdkVersion = 28
> > targetSdkVersion = 28
> > supportLibVersion = "28.0.0"
> > googlePlayServicesVersion="15.0.1"
> > }
> 
> I tried with this solution and with react-native-device-info latest version but the issue persist...

1.project build.gradle
2.ext node is the first level

**Comment by GabeConsalter** [comment]
For conflicts with different libraries versions, try to resolve changing this:
```
compile project(':react-native-device-info')
```
To this:
```
compile(project(':react-native-device-info')) {
    exclude group: 'com.google.android.gms'
}
```

**Comment by mikehardy** [comment]
@GabeConsalter no - just use the latest version of the library or - better - you should always pin your dependencies in android/build.gradle’s ext {} block by specifying `googlePlayServicesVersion`

https://github.com/react-native-community/react-native-device-info/commit/9588763593937d8944e6eb7535521719ee0eeb1e
