### ISSUE TITLE
hasNotch - wrong docs?

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-device-info#843]
# Bug

Sorry I'm not following the template, this is just a tiny issue with the docs. 

hasNotch does not appear in the v3 to v4 migration guide. However, shows as `boolean` return type on the docs, but uses a promise based example on the examples below. Which one is it? Promise or sync?

**Comment by mikehardy** [comment]
Ah - hasNotch is actually just a pure-javascript lookup table, so it should be simply boolean - https://github.com/react-native-community/react-native-device-info/blob/master/src/index.ts#L759 - PRs always appreciated for docs, thanks for noticing this :pray:

**Comment by mikehardy** [comment]
fixed :-)

**Comment by mohak1990** [comment]
Still facing the same issue. Returning promise on DeviceInfo.hasNotch() check and not a Boolean value.

**Comment by mikehardy** [comment]
I missed the type in the flow type definitions but @mohak1990 just fixed it in #881 :clap:
